"""
TASK 1: Query Generation with Gemma 3

Replaces the old template-based generator: instead of filling `{topic}` into
a handful of Romanian patterns, each query is generated by an instruction-tuned
Gemma 3 model that actually reads the document text.

Backends:
  - vllm         : batched, continuous-batching inference (default, fast)
  - transformers : plain HF generate (fallback / debugging / small runs)
  - none         : no model loaded, only prompt building (`--dry-run`)

The output schema is unchanged, so `analyze_query_metrics.py` and the task2
triplet scripts keep working:

    {"doc_id", "source", "type", "title", "queries", "num_queries", "metrics", ...}

The run is wall-clock bounded (`--time-budget-min`) and resumable
(`--resume`), so it fits inside a 2-hour SLURM allocation: whatever is
generated before the budget expires is already flushed to disk, and a second
job continues from where the first stopped.

Usage:
    python3 -m src.task1_queries.gemma_query_generation --help
    python3 -m src.task1_queries.gemma_query_generation --dry-run --max-docs 3
    python3 -m src.task1_queries.gemma_query_generation --max-docs 20000
"""

import argparse
import json
import os
import re
import sys
import time
from datetime import timedelta
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Tuple

_THIS_DIR = Path(__file__).resolve().parent
if str(_THIS_DIR) not in sys.path:
    sys.path.insert(0, str(_THIS_DIR))

from query_metrics import FastQueryMetrics, mean, std  # noqa: E402

try:
    from tqdm import tqdm
except ImportError:  # keeps --dry-run usable on a bare login node
    class _NoProgress:
        def update(self, n=1):
            pass

        def close(self):
            pass

    def tqdm(iterable=None, **kwargs):
        return iterable if iterable is not None else _NoProgress()


DEFAULT_MODEL = "google/gemma-3-4b-it"
DEFAULT_OUTPUT = "data/queries/queries_gemma3.jsonl"
DEFAULT_CATEGORIES_DIR = "data/categories"

# Categories that hold news articles (one directory per outlet).
NEWS_CATEGORIES = {
    "adevarul", "aleph", "cotidianul", "digi24", "evz", "libertatea",
    "mediafax", "news", "protv", "realitatea", "zf",
}

# `news/news.jsonl` is the concatenation of the ten outlet directories, same
# doc_ids and all. Processing both would generate every news query twice and
# scatter copies of one document across the train/test split, so the aggregate
# is skipped unless it is asked for by name or with --include-aggregates.
AGGREGATE_CATEGORIES = {"news"}


# --------------------------------------------------------------------------- #
# Document handling
# --------------------------------------------------------------------------- #

def category_to_type(category: str) -> str:
    """Map a category directory name to a document type."""
    category = category.lower()
    if category in NEWS_CATEGORIES:
        return "news"
    if category in ("recipes", "stories", "summarization"):
        return category
    return "unknown"


def document_text(doc: Dict[str, Any], doc_type: str, max_chars: int) -> str:
    """Build the text block shown to the model for one document."""
    title = (doc.get("title") or "").strip()
    parts: List[str] = []

    if title:
        parts.append(f"Titlu: {title}")

    if doc_type == "recipes":
        ingredients = (doc.get("ingredients") or "").strip()
        if ingredients:
            parts.append(f"Ingrediente: {ingredients}")
        body = (doc.get("content") or "").strip()
    elif doc_type == "stories":
        author = (doc.get("author") or "").strip()
        if author and author.lower() != "unknown":
            parts.append(f"Autor: {author}")
        body = (doc.get("content") or "").strip()
    else:
        body = (doc.get("text") or doc.get("content") or "").strip()
        if not body:
            body = (doc.get("summary") or "").strip()

    if body:
        parts.append(f"Text: {body}")

    text = "\n".join(parts).strip()
    if len(text) > max_chars:
        text = text[:max_chars].rsplit(" ", 1)[0] + " […]"
    return text


def _is_lfs_pointer(filepath: str) -> bool:
    """True for a git-lfs pointer file that was never fetched (`git lfs pull`)."""
    try:
        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            return f.readline().startswith("version https://git-lfs")
    except OSError:
        return False


def usable_categories(
    categories_dir: str,
    categories: Optional[List[str]] = None,
    include_aggregates: bool = False,
    verbose: bool = True,
) -> List[str]:
    """Category directories to read, in a stable order.

    An explicit --categories selection always wins, so `--categories news`
    still works when the aggregate is what you actually want.
    """
    if not os.path.isdir(categories_dir):
        raise FileNotFoundError(f"Categories directory not found: {categories_dir}")

    wanted = {c.lower() for c in categories} if categories else None
    selected = []

    for category in sorted(os.listdir(categories_dir)):
        if not os.path.isdir(os.path.join(categories_dir, category)):
            continue
        if category_to_type(category) == "unknown":
            if verbose:
                print(f"  ⚠ Skipping unknown category: {category}")
            continue
        if wanted is not None:
            if category.lower() in wanted:
                selected.append(category)
            continue
        if category.lower() in AGGREGATE_CATEGORIES and not include_aggregates:
            if verbose:
                print(f"  ▸ Skipping aggregate category '{category}' "
                      f"(duplicates the per-outlet directories; "
                      f"--include-aggregates to keep it)")
            continue
        selected.append(category)

    return selected


def iter_documents(
    categories_dir: str,
    categories: Optional[List[str]] = None,
    per_category: Optional[int] = None,
    stride: int = 1,
    include_aggregates: bool = False,
) -> Iterator[Tuple[Dict[str, Any], str]]:
    """Stream (document, doc_type) pairs from the category JSONL files."""
    for category in usable_categories(categories_dir, categories, include_aggregates):
        category_path = os.path.join(categories_dir, category)
        doc_type = category_to_type(category)

        emitted = 0
        for filename in sorted(os.listdir(category_path)):
            if not filename.endswith(".jsonl"):
                continue
            filepath = os.path.join(category_path, filename)
            if _is_lfs_pointer(filepath):
                print(f"  ⚠ {filepath} is an unfetched git-lfs pointer - run `git lfs pull`")
                continue

            with open(filepath, "r", encoding="utf-8") as f:
                for index, line in enumerate(f):
                    if per_category is not None and emitted >= per_category:
                        break
                    if not line.strip():
                        continue
                    if index % stride != 0:
                        continue
                    try:
                        doc = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    doc.setdefault("category", category)
                    yield doc, doc_type
                    emitted += 1

            if per_category is not None and emitted >= per_category:
                break


def count_categories(
    categories_dir: str,
    categories: Optional[List[str]],
    include_aggregates: bool = False,
) -> int:
    """Number of category directories that will be read (for balanced sampling)."""
    return len(usable_categories(categories_dir, categories, include_aggregates,
                                verbose=False))


# --------------------------------------------------------------------------- #
# Prompting
# --------------------------------------------------------------------------- #

TYPE_HINTS = {
    "news": (
        "Documentul este un articol de presă. Concentrează-te pe evenimentul relatat, "
        "persoanele și instituțiile implicate, cifre, cauze și consecințe."
    ),
    "summarization": (
        "Documentul este un articol cu rezumat. Concentrează-te pe subiectul principal, "
        "datele concrete și implicațiile lui."
    ),
    "stories": (
        "Documentul este un fragment literar. Formulează întrebări despre acțiune, "
        "personaje, locuri și teme, folosind numele proprii care apar în text."
    ),
    "recipes": (
        "Documentul este o rețetă culinară. FIECARE întrebare trebuie să conțină "
        "explicit numele preparatului/rețetei exact sau într-o formă naturală derivată din titlu. "
        "Formulează întrebări despre ingrediente, cantități, mod de preparare și variante."
    ),
}

PROMPT_TEMPLATE = """Ești expert în regăsirea informației (information retrieval) pentru limba română.

Primești un document și generezi exact {n} întrebări de căutare distincte la care documentul răspunde.

{type_hint}

Reguli obligatorii:
1. Scrie în limba română corectă, cu diacritice.
2. Fiecare întrebare trebuie să aibă răspuns în documentul de mai jos.
3. Întrebările trebuie să fie autonome: NU folosi „acest articol”, „textul de mai sus”, „documentul”, „autorul”. Cineva care nu a văzut documentul trebuie să înțeleagă întrebarea.
4. Folosește termeni concreți din document (nume, locuri, instituții, cifre, produse), nu formulări generice.
5. Variază tipul întrebărilor: factuală, cauzală („de ce”), procedurală („cum”), context sau consecințe.
6. Fiecare întrebare are între 5 și 25 de cuvinte și se termină cu semnul întrebării.
7. Nu repeta aceeași întrebare reformulată.

Răspunde DOAR cu un array JSON de {n} șiruri de caractere, fără text suplimentar și fără explicații.

DOCUMENT:
{document}

JSON:"""


PROMPT_V2_MULTI_DOC = """Ești expert în regăsirea informației (information retrieval) pentru limba română.

Primești titlul și articolul original + 1-2 articole similare. Generează 2-3 întrebări suficient de generale
încât să fie relevante pentru toate articolele, nu doar pentru articolul original.

{type_hint}

Reguli obligatorii:
1. Scrie în limba română corectă, cu diacritice.
2. Fiecare întrebare trebuie să aibă răspuns în TOATE articolele (originalul + similare).
3. Întrebările trebuie să fie autonome: NU folosi „acest articol", „textul de mai sus", „documentul", „autorul". Cineva care nu a văzut documentele trebuie să înțeleagă întrebarea.
4. Folosește termeni concreți (nume, locuri, instituții, cifre, produse) din articolul original, dar formuleaza generalizat să acopere și articolele similare.
5. Variază tipul întrebărilor: factuală, cauzală („de ce"), procedurală („cum"), context sau consecințe.
6. Fiecare întrebare are între 5 și 25 de cuvinte și se termină cu semnul întrebării.
7. NU genera întrebări redundante sau de tip \"text-based retrieval\".
8. Dacă nu poți genera 2-3 diverse și relevante pentru toate articolele, generează doar 1 bună.

Răspunde DOAR cu un array JSON de șiruri de caractere (2-3 întrebări), fără text suplimentar și fără explicații.

TITLU ARTICOL ORIGINAL:
{title}

ARTICOL ORIGINAL:
{content}

ARTICOLE SIMILARE (context suplimentar):
{similar_articles}

JSON:"""


def build_prompt(doc: Dict[str, Any], doc_type: str, num_queries: int, max_chars: int) -> Optional[str]:
    """Build the user message for one document, or None if the document is unusable."""
    text = document_text(doc, doc_type, max_chars)
    if len(text) < 80:
        return None
    return PROMPT_TEMPLATE.format(
        n=num_queries,
        type_hint=TYPE_HINTS.get(doc_type, ""),
        document=text,
    )


# --------------------------------------------------------------------------- #
# Output parsing
# --------------------------------------------------------------------------- #

BANNED_PATTERNS = [
    r"acest (articol|text|document|fragment)",
    r"textul de mai sus",
    r"\bîn document\b",
    r"documentul de mai sus",
    r"pasajul de mai sus",
]

_JSON_ARRAY = re.compile(r"\[.*?\]", re.DOTALL)
_LIST_PREFIX = re.compile(r'^\s*(?:[-*•]|\d+[.)])\s*')


def _clean_candidate(raw: str) -> str:
    text = _LIST_PREFIX.sub("", raw.strip())
    text = text.strip().strip('",').strip()
    if text.startswith(("'", '"')) and text.endswith(("'", '"')) and len(text) > 1:
        text = text[1:-1].strip()
    return re.sub(r"\s+", " ", text)


def _as_string_list(parsed: Any) -> List[str]:
    if not isinstance(parsed, list):
        return []
    return [str(item) for item in parsed if isinstance(item, (str, int, float))]


def _extract_candidates(text: str) -> List[str]:
    """Pull query strings out of model output that may not be valid JSON."""
    match = _JSON_ARRAY.search(text)
    if match:
        try:
            candidates = _as_string_list(json.loads(match.group(0)))
            if candidates:
                return candidates
        except json.JSONDecodeError:
            pass

    # Truncated array (the model hit max_new_tokens): close it and retry.
    if "[" in text:
        fragment = text[text.index("["):].rstrip()
        for repaired in (fragment + "]", fragment.rstrip(",") + "]",
                         fragment.rsplit(",", 1)[0] + "]"):
            try:
                candidates = _as_string_list(json.loads(repaired))
                if candidates:
                    return candidates
            except json.JSONDecodeError:
                continue

    # Any quoted strings left over from a half-written array.
    quoted = re.findall(r'"([^"\n]{8,300})"', text)
    if quoted:
        return quoted

    # Last resort: numbered lists, bullets, bare questions.
    return [line for line in text.splitlines() if "?" in line]


def parse_queries(raw_output: str, max_queries: int) -> List[str]:
    """Extract queries from the model output, tolerating malformed JSON."""
    text = raw_output.strip()
    text = re.sub(r"^```(?:json)?|```$", "", text, flags=re.MULTILINE).strip()

    candidates = _extract_candidates(text)

    queries: List[str] = []
    seen = set()
    for candidate in candidates:
        query = _clean_candidate(candidate)
        if not query:
            continue
        if not query.endswith("?"):
            # Keep a trailing question if the model appended stray punctuation.
            if "?" in query:
                query = query[:query.rindex("?") + 1].strip()
            else:
                continue
        words = query.split()
        if not (4 <= len(words) <= 30):
            continue
        lowered = query.lower()
        if any(re.search(p, lowered) for p in BANNED_PATTERNS):
            continue
        if "{" in query or "}" in query:
            continue
        key = re.sub(r"[^\w]+", "", lowered)
        if key in seen:
            continue
        seen.add(key)
        queries.append(query)
        if len(queries) >= max_queries:
            break

    return queries


# --------------------------------------------------------------------------- #
# Backends
# --------------------------------------------------------------------------- #

class VLLMBackend:
    """Batched generation with vLLM (continuous batching)."""

    name = "vllm"

    def __init__(self, args):
        from transformers import AutoTokenizer
        from vllm import LLM, SamplingParams

        print(f"▸ Loading {args.model} with vLLM …")
        self.tokenizer = AutoTokenizer.from_pretrained(args.model)
        self.llm = LLM(
            model=args.model,
            dtype=args.dtype,
            max_model_len=args.max_model_len,
            gpu_memory_utilization=args.gpu_memory_utilization,
            tensor_parallel_size=args.tensor_parallel_size,
            seed=args.seed,
            trust_remote_code=True,
        )
        self.sampling_params = SamplingParams(
            temperature=args.temperature,
            top_p=args.top_p,
            max_tokens=args.max_new_tokens,
            seed=args.seed,
        )

    def _to_token_ids(self, prompt: str) -> List[int]:
        # Single user turn: Gemma chat templates do not accept a system role.
        # Tokenize here rather than handing vLLM a string: the chat template
        # already emits <bos>, and vLLM would prepend a second one.
        return self.tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=True,
            add_generation_prompt=True,
        )

    def generate(self, prompts: List[str]) -> List[str]:
        requests = [{"prompt_token_ids": self._to_token_ids(p)} for p in prompts]
        outputs = self.llm.generate(requests, self.sampling_params, use_tqdm=False)
        return [o.outputs[0].text for o in outputs]


class TransformersBackend:
    """Plain HF `generate`, for debugging or when vLLM is unavailable."""

    name = "transformers"

    def __init__(self, args):
        import torch
        from transformers import AutoTokenizer

        print(f"▸ Loading {args.model} with transformers …")
        self.torch = torch
        self.tokenizer = AutoTokenizer.from_pretrained(args.model, padding_side="left")
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        dtype = {
            "bfloat16": torch.bfloat16,
            "float16": torch.float16,
            "float32": torch.float32,
        }.get(args.dtype, "auto")

        self.model = self._load_model(args.model, dtype)
        self.model.eval()
        self.args = args

    @staticmethod
    def _load_model(model_name: str, dtype):
        """Gemma 3 4b+ ships as a multimodal checkpoint; 1b is text-only."""
        import transformers

        errors = []
        for cls_name in ("AutoModelForCausalLM", "AutoModelForImageTextToText"):
            cls = getattr(transformers, cls_name, None)
            if cls is None:
                continue
            try:
                return cls.from_pretrained(model_name, torch_dtype=dtype, device_map="auto")
            except (ValueError, KeyError, OSError) as exc:
                errors.append(f"{cls_name}: {exc}")
        raise RuntimeError("Could not load model. Tried:\n  " + "\n  ".join(errors))

    def generate(self, prompts: List[str]) -> List[str]:
        chats = [
            self.tokenizer.apply_chat_template(
                [{"role": "user", "content": p}],
                tokenize=False,
                add_generation_prompt=True,
            )
            for p in prompts
        ]
        inputs = self.tokenizer(
            chats,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=self.args.max_model_len - self.args.max_new_tokens,
            add_special_tokens=False,
        ).to(self.model.device)

        with self.torch.inference_mode():
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=self.args.max_new_tokens,
                do_sample=self.args.temperature > 0,
                temperature=self.args.temperature,
                top_p=self.args.top_p,
                pad_token_id=self.tokenizer.pad_token_id,
            )

        generated = outputs[:, inputs["input_ids"].shape[1]:]
        return self.tokenizer.batch_decode(generated, skip_special_tokens=True)


def build_backend(args):
    """Instantiate the requested backend, falling back to transformers."""
    if args.backend == "none":
        return None
    if args.backend in ("vllm", "auto"):
        try:
            return VLLMBackend(args)
        except Exception as exc:
            if args.backend == "vllm":
                raise
            print(f"⚠ vLLM unavailable ({exc}); falling back to transformers.")
    return TransformersBackend(args)


# --------------------------------------------------------------------------- #
# Generation run
# --------------------------------------------------------------------------- #

def load_done_ids(output_path: str) -> set:
    """Doc ids already present in a previous (possibly interrupted) run."""
    done = set()
    if not os.path.exists(output_path):
        return done
    with open(output_path, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            try:
                done.add(json.loads(line).get("doc_id"))
            except json.JSONDecodeError:
                continue
    done.discard(None)
    return done


def print_stats(stats: Dict[str, Dict[str, Any]], elapsed: float, docs_done: int) -> None:
    print("\n" + "=" * 70)
    print("GEMMA QUERY GENERATION - FINAL REPORT")
    print("=" * 70)

    print("\n📊 QUERIES GENERATED BY TYPE:")
    total = 0
    for doc_type in sorted(stats):
        count = stats[doc_type]["count"]
        total += count
        print(f"  {doc_type:<20} {count:>8} queries  ({stats[doc_type]['docs']} docs)")
    print(f"  {'─' * 30}")
    print(f"  {'TOTAL':<20} {total:>8} queries")

    print("\n📈 QUALITY METRICS BY TYPE:")
    for doc_type in sorted(stats):
        scores = stats[doc_type]["quality_scores"]
        if scores:
            print(
                f"  {doc_type:<20} avg={mean(scores):.3f} ± {std(scores):.3f} "
                f"(min={min(scores):.2f}, max={max(scores):.2f})"
            )

    rate = docs_done / elapsed if elapsed > 0 else 0.0
    print(f"\n⏱  {docs_done} documents in {timedelta(seconds=int(elapsed))} "
          f"({rate:.2f} docs/s, {rate * 3600:.0f} docs/h)")
    print("=" * 70)


def run(args) -> None:
    output_path = args.output
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    done_ids = load_done_ids(output_path) if args.resume else set()
    if args.resume and done_ids:
        print(f"▸ Resuming: {len(done_ids)} documents already generated.")
    elif not args.resume and os.path.exists(output_path):
        print(f"▸ Overwriting existing {output_path} (use --resume to continue instead).")
        open(output_path, "w", encoding="utf-8").close()

    per_category = args.per_category
    if per_category is None and args.max_docs:
        n_cats = count_categories(args.categories_dir, args.categories,
                                  args.include_aggregates)
        if n_cats:
            per_category = -(-args.max_docs // n_cats)  # ceil, balanced sampling
            print(f"▸ Balanced sampling: {per_category} documents from each of {n_cats} categories.")

    metrics = FastQueryMetrics()
    stats: Dict[str, Dict[str, Any]] = {}
    backend = build_backend(args)

    deadline = time.monotonic() + args.time_budget_min * 60 if args.time_budget_min > 0 else None
    started = time.monotonic()
    docs_done = 0
    written = 0
    skipped_short = 0
    skipped_unparsed = 0
    budget_hit = False

    documents = iter_documents(
        args.categories_dir,
        categories=args.categories,
        per_category=per_category,
        stride=args.stride,
        include_aggregates=args.include_aggregates,
    )

    batch_docs: List[Tuple[Dict[str, Any], str]] = []
    batch_prompts: List[str] = []

    progress = tqdm(total=args.max_docs or None, desc="Generating", unit="doc")
    out_file = open(output_path, "a", encoding="utf-8")

    def flush_batch() -> None:
        nonlocal written, skipped_unparsed, docs_done

        if not batch_prompts:
            return

        if backend is None:  # --dry-run
            raw_outputs = ["[]"] * len(batch_prompts)
        else:
            raw_outputs = backend.generate(batch_prompts)

        for (doc, doc_type), raw in zip(batch_docs, raw_outputs):
            queries = parse_queries(raw, args.queries_per_doc)
            record_metrics = metrics.score_record(queries, doc) if queries else {}

            if queries and args.min_quality > 0:
                keep = [
                    q for q, s in zip(queries, record_metrics["quality_scores"])
                    if s >= args.min_quality
                ]
                if len(keep) != len(queries):
                    queries = keep
                    record_metrics = metrics.score_record(queries, doc) if queries else {}

            if not queries:
                skipped_unparsed += 1

            record = {
                "doc_id": doc.get("doc_id", ""),
                "source": doc.get("source", ""),
                "category": doc.get("category", ""),
                "type": doc_type,
                "title": doc.get("title", ""),
                "queries": queries,
                "num_queries": len(queries),
                "metrics": record_metrics,
                "generator": args.model,
            }
            out_file.write(json.dumps(record, ensure_ascii=False) + "\n")
            written += 1

            bucket = stats.setdefault(doc_type, {"count": 0, "docs": 0, "quality_scores": []})
            bucket["count"] += len(queries)
            bucket["docs"] += 1
            bucket["quality_scores"].extend(record_metrics.get("quality_scores", []))

        out_file.flush()
        docs_done += len(batch_docs)
        batch_docs.clear()
        batch_prompts.clear()

    try:
        for doc, doc_type in documents:
            if args.max_docs and docs_done + len(batch_docs) >= args.max_docs:
                break
            if deadline and time.monotonic() >= deadline:
                budget_hit = True
                break

            doc_id = doc.get("doc_id", "")
            if doc_id in done_ids:
                continue

            prompt = build_prompt(doc, doc_type, args.queries_per_doc, args.max_doc_chars)
            if prompt is None:
                skipped_short += 1
                continue

            if args.dry_run:
                print("\n" + "─" * 70)
                print(f"[{doc_type}] {doc_id}")
                print("─" * 70)
                print(prompt)
                docs_done += 1
                if args.max_docs and docs_done >= args.max_docs:
                    break
                continue

            batch_docs.append((doc, doc_type))
            batch_prompts.append(prompt)

            if len(batch_prompts) >= args.batch_size:
                flush_batch()
                progress.update(args.batch_size)

        if not args.dry_run:
            flush_batch()
    except KeyboardInterrupt:
        print("\n⚠ Interrupted - flushing what has been generated so far.")
        if not args.dry_run:
            flush_batch()
    finally:
        out_file.close()
        if hasattr(progress, "close"):
            progress.close()

    if args.dry_run:
        print(f"\n✓ Dry run: built prompts for {docs_done} documents (no model loaded).")
        return

    elapsed = time.monotonic() - started
    print(f"\n✓ Wrote {written} records to {output_path}")
    if skipped_short:
        print(f"  ({skipped_short} documents skipped: text too short)")
    if skipped_unparsed:
        print(f"  ({skipped_unparsed} documents produced no usable query)")
    if budget_hit:
        print(f"  ⏳ Time budget of {args.time_budget_min} min reached - "
              f"rerun with --resume to continue.")

    print_stats(stats, elapsed, docs_done)

    stats_path = output_path + ".stats.json"
    with open(stats_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "config": vars(args),
                "elapsed_seconds": round(elapsed, 1),
                "documents": docs_done,
                "records_written": written,
                "budget_reached": budget_hit,
                "by_type": {
                    t: {
                        "docs": s["docs"],
                        "queries": s["count"],
                        "avg_quality": round(mean(s["quality_scores"]), 4),
                        "std_quality": round(std(s["quality_scores"]), 4),
                    }
                    for t, s in stats.items()
                },
            },
            f,
            indent=2,
            ensure_ascii=False,
        )
    print(f"✓ Run manifest: {stats_path}")


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate Romanian retrieval queries from documents with Gemma 3.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    model_group = parser.add_argument_group("model")
    model_group.add_argument("--model", default=os.environ.get("GEMMA_MODEL", DEFAULT_MODEL),
                             help="HuggingFace model id (gated: accept the Gemma license first)")
    model_group.add_argument("--backend", default=os.environ.get("QGEN_BACKEND", "auto"),
                             choices=["auto", "vllm", "transformers", "none"])
    model_group.add_argument("--dtype", default="bfloat16",
                             choices=["auto", "bfloat16", "float16", "float32"],
                             help="use float16 on GPUs without bf16 support (e.g. V100)")
    model_group.add_argument("--max-model-len", type=int, default=2048)
    model_group.add_argument("--max-new-tokens", type=int, default=192)
    model_group.add_argument("--temperature", type=float, default=0.8)
    model_group.add_argument("--top-p", type=float, default=0.95)
    model_group.add_argument("--gpu-memory-utilization", type=float, default=0.90)
    model_group.add_argument("--tensor-parallel-size", type=int, default=1)
    model_group.add_argument("--seed", type=int, default=42)

    data_group = parser.add_argument_group("data")
    data_group.add_argument("--categories-dir", default=DEFAULT_CATEGORIES_DIR)
    data_group.add_argument("--categories", nargs="+", default=None,
                            help="only these category directories (default: all)")
    data_group.add_argument("--output", default=os.environ.get("QGEN_OUTPUT", DEFAULT_OUTPUT))
    data_group.add_argument("--max-docs", type=int, default=20000,
                            help="total document budget (0 = no limit)")
    data_group.add_argument("--per-category", type=int, default=None,
                            help="per-category cap (default: max-docs split evenly)")
    data_group.add_argument("--stride", type=int, default=1,
                            help="take every Nth document for a spread-out sample")
    data_group.add_argument("--include-aggregates", action="store_true",
                            help="also read data/categories/news/, which duplicates "
                                 "the ten per-outlet directories")
    data_group.add_argument("--max-doc-chars", type=int, default=2000)

    run_group = parser.add_argument_group("run")
    run_group.add_argument("--queries-per-doc", type=int, default=4)
    run_group.add_argument("--batch-size", type=int, default=256,
                           help="use ~8 for the transformers backend")
    run_group.add_argument("--min-quality", type=float, default=0.0,
                           help="drop queries below this heuristic quality score")
    run_group.add_argument("--time-budget-min", type=float,
                           default=float(os.environ.get("QGEN_TIME_BUDGET_MIN", 110)),
                           help="stop cleanly after this many minutes (0 = unlimited)")
    run_group.add_argument("--resume", action="store_true",
                           help="append to the output file, skipping documents already done")
    run_group.add_argument("--dry-run", action="store_true",
                           help="print prompts without loading a model")

    args = parser.parse_args(argv)
    if args.dry_run:
        args.backend = "none"
        if args.max_docs == 20000:
            args.max_docs = 3
    if args.backend == "transformers" and args.batch_size > 32:
        print("▸ Lowering batch size to 8 for the transformers backend.")
        args.batch_size = 8
    return args


def main(argv=None) -> None:
    args = parse_args(argv)

    print("\n" + "=" * 70)
    print("TASK 1: QUERY GENERATION WITH GEMMA 3")
    print("=" * 70)
    print(f"  model        : {args.model}")
    print(f"  backend      : {args.backend}")
    print(f"  output       : {args.output}")
    print(f"  doc budget   : {args.max_docs or 'all'}")
    print(f"  time budget  : {args.time_budget_min or 'unlimited'} min")
    print(f"  queries/doc  : {args.queries_per_doc}")

    run(args)


if __name__ == "__main__":
    main()
